# -*- coding: utf-8 -*-
"""
Hash Map dos grupos empresariais -> unidades/filiais (dados normalizados).

Estrutura:  { 'Nome do Grupo': ['Unidade 1', 'Unidade 2', ...] }
  - Nivel 1 (chave)  -> pasta-mae no Drive, criada como  'Grupo ' + chave
  - Nivel 2 (lista)  -> subpastas (uma por unidade), dentro da pasta-mae

Gerado a partir de relatorio.txt e validado manualmente (153 grupos / 377 unidades).
NAO editar a mao sem necessidade; alteracoes de agrupamento devem ser refeitas na origem.
"""

COMPANY_GROUPS: dict[str, list[str]] = {'JANE': ['JANE ALVES'],
 'EM': ['EM SI PSICOLOGIA'],
 'RUTE': ['RUTE ALVES DE SÁ'],
 'RITOCA': ['RITOCA'],
 'MASTER': ['MASTER'],
 'Ipac': ['Ipac Contabilidade', 'Ipac Prime', 'IPAC PREMIUM'],
 'ZAMBRI': ['ZAMBRI'],
 'Coco Bambu': ['CB LAGO SUL',
                'CB PARKSHOPPING',
                'CB IGUATEMI',
                'CB SAO JOSÉ DO RIO PRETO',
                'CB Botafogo',
                'CB Norte Shopping',
                'CB CONCEITO JK VILA OLIMPIA (MATRIZ DOS CONCEITOS)',
                'CB DEPOSITO (FILIAL 1 CONCEITO)',
                'CB ELDORADO (FILIAL 2 CONCEITO)',
                'CB PATIO PAULISTA (FILIAL 3 CONCEITO)',
                'CB AF COMERCIO DE ALIMENTOS LTDA',
                'CB RP COMERCIO DE ALIMENTOS LTDA',
                'CB MARKET PLACE COMERCIO DE ALIMENTOS LTDA',
                'CB CAMPINAS COMERCIO DE ALIMENTOS LTDA',
                'CB ANHEMBI COMERCIO DE ALIMENTOS LTDA',
                'CB ALPHAVILLE COMERCIO DE ALIMENTOS LTDA',
                'CB SP MARKET COMERCIO DE ALIMENTOS LTDA',
                'CB SANTO ANDRE COMERCIO DE ALIMENTOS LTDA',
                'CB OSASCO COMERCIO DE ALIMENTOS LTDA',
                'CB GUARULHOS COMERCIO DE ALIMENTOS LTDA',
                'CB SOROCABA COMERCIO DE ALIMENTOS',
                'CB São Bernardo do Campo (FILIAL STO ANDRE)',
                'CB HADDOCK',
                'CB CONCEITO TIVOLI - (FILIAL CAMPINAS - 361)',
                'CB Jundiaí - NOVA',
                'CB ANAPOLIS',
                'CB BELÉM',
                'CB Iguatemi Na Praia',
                'CB Info',
                'CB NITEROI',
                'CB São José dos Campos',
                'CB MANAUS',
                'CB Granja Viana',
                'CB GOIANIA FILIAL',
                'CB CONCEITO JK - FILIAL BOURBON',
                'CB JK - Tietê Plaza',
                'CB LIMEIRA (FILIAL JUNDIAI)',
                'CB MARKET PLACE - FILIAL COCO BAMBU MORUMBI',
                'CB MACEIÓ COMÉRCIO DE ALIMENTOS LTDA',
                'CB BOA VISTA',
                'CB RECREIO - FILIAL DA CB BARRA',
                'CB ARARAQUARA - FILIAL CB RP',
                'CB VOLTA REDONDA',
                'CB TATUAPE - FILIAL DA ANALIA FRANCO',
                'CB ITAQUERA - FILIAL ANALIA FRANCO',
                'CB GRANDE RIO FILIAL DA CB VOLTA REDONDA',
                'CB CAMPINAS FILIAL JARDIM DO LAGO - FILIAL CAMPINAS 361',
                'CB RIO TIJUCA - FILIAL CB BOTAFOGO',
                'CB TECH SERVIÇOS DE TECNOLOGIA LTDA',
                'CB PRAIA GRANDE LTDA',
                'C.B. BRASILIA',
                'COCO BAMBU - GOIÂNIA',
                'COCO BAMBU BARRA DA TIJUCA',
                'Coco Bambú Águas Claras',
                'Coco Bambu Plaza Sul -filial JK',
                'Coco Bambu Rio Carioca Shopping',
                'Coco Bambu Tucuruvi',
                'Vasto Restaurante - Filial CB Brasília',
                'Vasto Lago Sul - Filial CB Lago Sul',
                'CBX Coco Bambu Campo Grande',
                'CBJK',
                'Cb TGS Aguas Claras',
                'FILIAL CB MANAUS'],
 'LG': ['LG'],
 'PROTEÍNAS': ['PROTEÍNAS'],
 'MAP': ['MAP'],
 'LIMA': ['LIMA DIAS'],
 'LUID': ['LUID - Doméstica'],
 'SMA': ['SMA'],
 'NUNES': ['NUNES E AMARAL'],
 'ITIGP': ['ITIGP - Instituto de Tec. Inf. Gestao e Projetos Ltda'],
 'Instituto Omnis': ['Instituto Omnis'],
 'Instituto de Tricologia': ['Instituto de Tricologia'],
 'Instituto Publix': ['Instituto Publix'],
 'BHUMI': ['BHUMI'],
 'KR': ['KR SERVIÇOS DE ODONTOLOGIA - TAGUATINGA', 'KR Serviços de Ondontologia - Samambaia- Matriz'],
 'Mr. Magoo': ['Mr. Magoo'],
 'Belini': ['Belini Pães e Gastronomia Ltda'],
 'La Paneteria': ['LA PANETERIA'],
 'Pão Brasilis': ['PÃO BRASILIS'],
 'GKR': ['GKR SERVIÇOS DE ODONTOLOGIA'],
 'Qualycream': ['Qualycream Comércio'],
 'Implantec': ['Implantec Laboratorio',
               'Implantec Harmonização Orofacial',
               'Implantec Lago Sul',
               'Implantec Harmonização facial Lago Sul',
               'IMPLANTEC TAGUATINGA'],
 'LE': ['LE TERRACE', 'LE PARISIEN'],
 'Up Back': ['UP BACK',
             'UP SOLUTIONS',
             'UP BACK FILIAL',
             'UP BACK BUFFET COZINHA INDUSTRIAL',
             'Up Back Filial 2',
             'Up Back Buffet Filial'],
 'Walk Pharma': ['WALKMED PHARMA EIRELI', 'WALKLAB BIOTECH PHARMA LTDA', 'WALKPHARMA COMERCIO E SERVIÇO LTDA'],
 'OH Artes Publicidades': ['OH, ARTES PUBLICIDADES'],
 'MAITE': ['MAITE SCHENDES GRANADO BARBOSA'],
 'Estrutural': ['Estrutural S.A'],
 'TULIO': ['TULIO BASTOS'],
 'Capilar': ['Capilar Comércio de Cosméticos'],
 'Cabral': ['Cabral Home Care'],
 'Neli': ['Neli Gonçalves Ferreira'],
 'NP': ['NP Treinamentos'],
 'ME': ['ME Componentes e Equipamentos'],
 'IED': ['IED Assistência Médica'],
 'VANDA': ['VANDA ELIZIA'],
 'Segredo': ['Segredo Capital'],
 'Centro': ['Centro de Reabilitação Sarah Brandão'],
 'FERROMIL': ['FERROMIL COMERCIAL DE FERRAGENS LTDA - EPP'],
 'FERRO': ['FERRO & ACO COMERCIAL DE FERRAGENS 130DF EIRELI - EPP'],
 'ORTOSHOW': ['ORTOSHOW PREMIER'],
 'CLÍNICA': ['CLÍNICA RIZZA'],
 'LD': ['LD COM DE EQUIPAMENTOS DE ILUMINACAO LTDA'],
 'Fison': ['Fison Comércio e Representações', 'Fison Filial'],
 'Viva': ['VIVA MULTICLINICA', 'Viva Laser BSB'],
 'Int': ['Int Soluções'],
 'Holding': ['Torres Par',
             'TORRES INVESTIMENTOS E PARTICIPACOES S.A',
             'BP PARTICIPAÇÕES',
             'Queiroz Studart Participações - Eilson',
             'QS HOLDING FAMILIAR LTDA - EMPRESA EILSON',
             'OLYMPIA PARTICIPACOES',
             'ALTEVITA PARTICIPAÇOES LTDA',
             'SIX SPORT LIFE PARTICIPAÇÕES LTDA',
             'LAMAT PARTICIPACOES',
             'ASTON PARTICIPAÇÕES',
             'FUTUREMED PARTICIPAÇÕES',
             'LUNA PARTICIPACOES LTDA',
             'MTB PARTICIPAÇÕES LTDA',
             'LMRS HOLDING LTDA',
             'PC HEALTH HOLDING',
             'RALB PARTICIPACOES LTDA',
             '3PAR HOLDING LTDA',
             'DUO PARTICIPAÇÕES LTDA',
             'CSAL Participações LTDA -',
             'NMP PARTICIPAÇÕES LTDA - EM CONSTIUÇÃO',
             'MKBM PARTICIPAÇOES LTDA',
             'RV Participações',
             'VILLALVA & GONDIM HOLDING LTDA',
             'GLOBETROTTER PARTICIPAÇÕES LTDA',
             'SANTIERE PARTICIPAÇÕES LTDA',
             'AGFA  PARTICIPAÇÕES LTDA',
             'BASBOR PARTICIPAÇÕES LTDA',
             'BUGREPAR PARTICIPACOES LTDA',
             'MAR EMPREENDIMENTOS - HOLDING EDSON MARIETTA',
             'TRIADI PARTICIPAÇÕES',
             'CVX PARTICIPACOES LTDA',
             'CH&ALC PARTICIPACOES LTDA',
             'HOLDING GUILHERME INDICAÇÃO MARCELINHO - EM CONSTITUIÇÃO',
             'IFBF  HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'SJP HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'MPB HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'DDM HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'MDN HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'LCB HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'PVM HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'VHB HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'DPD HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'RSB HOLDING DE PARTICIPAÇÕES E  PATRIMONIAL LTDA',
             'ARPPAR HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'LCF HOLDING DE PARTICIPAÇÕES E PATRIMONIAL LTDA',
             'MOSCA BRANCA DE INVESTIMENTOS E PARTICIPAÇÕES',
             'AVREN PAR LTDA',
             'M3 LEGACY PARTICIPAÇÕES LTDA',
             'JV CAPITAL PARTICIPACOES',
             'FERRARONI PARTICIPACOES LTDA',
             'GDC HOLDING DE PARTICIPACOES E PATRIMONIAL LTDA',
             'MAZAL PARTICIPAÇÕES LTDA',
             'FL RIBEIRO PARTICIPAÇÕES - EM CONSTITUIÇÃO'],
 'A&M': ['A&M Clinica Odontológica'],
 'ALDE': ['ALDE PEDIATRIA'],
 'ESPAR': ['ESPAR'],
 'Brasil': ['Brasil Ostar Internacional'],
 'M&C': ['M&C SERVICOS DE LAVANDERIA', 'M&C Lavanderia - Filial 1', 'M&C Lavanderia - Filial 2'],
 'Endo': ['Endo Saude Assistencia Medica'],
 'SPE': ['SPE Chehab'],
 'AMTT': ['AMTT CBC GESTÃO', 'AMTT CBC COMÉRCIO', 'AMTT CBC CLUBE DE TIRO'],
 'Via': ['Via spezia'],
 'IORE': ['IORE'],
 'RONAN': ['RONAN BRAGA'],
 'MP&CD': ['MP&CD Consultoria e Treinamento'],
 'Eilson': ['Camara Studart', 'STUDART SERVIÇOS MÉDICOS E EDUCACIONAL LTDA'],
 'J Marques': ['J MARQUES LTDA'],
 'MALI': ['MALI PRODUÇÕES ARTÍSTICAS LTDA'],
 'Dona Lenha': ['RP Alimentação - Dona Lenha', 'L&C ALIMENTAÇÃO Dona Lenha'],
 'P&D': ['P&D LAVANDERIA', 'P&D Filial'],
 'Alves': ['Alves e Coelho'],
 'MARZUK': ['MARZUK MATRIZ ASA SUL',
            'MARZUK FILIAL ASA NORTE',
            'MARZUK FILIAL MANE MERCADO',
            'MARZUK FILIAL SUDOESTE',
            'MARZUK FILIAL ASA SUL'],
 'GWP': ['GWP & H ALIMENTACAO E NEGOCIOS'],
 'OCT': ['OCT ALIMENTACAO'],
 'Longevitta': ['Longevitta Centro Geriátrico - Matriz', 'Longevittá Filial'],
 'Altevita': ['Espaço de Convivência', 'Altevita Care', 'ALTEVITA VIVERE LTDA'],
 'Tarso': ['Espaço Strogonoff LTDA', 'Tarso Restaurante LTDA'],
 'Manga': ['MANGA CO LTDA', 'MANGA II', 'MANGA SIGMA LTDA', 'Filal da Manga CO - MANGA.CO IDP'],
 'FLOR': ['FLOR DE SAL LTDA'],
 'MUSICA': ['MUSICA E ARQUITETURA'],
 'SIX': ['SIX NOROESTE',
         'SIX LAGO SUL',
         'SIX SAO PAULO LTDA',
         'SIX JARDINS LTDA -  EM CONSTITUIÇÃO',
         'SIX HEALTH LTDA',
         'SIX CAMPINAS',
         'SIX VILA NOVA CONCEIÇÃO',
         'SIX ALPHAVILLE LTDA',
         'SIX WELLNESS CLUB LTDA',
         'SIX EXPERIENCE LTDA',
         'SIX BH'],
 'LDI': ['LDI ATACADISTA LTDA'],
 'CRP': ['CRP CLÍNICA MÉDICA LTDA', 'CRP FILIAL'],
 'EPM': ['EPM SERVIÇOS DE APOIO TÉCNICO E ADMINISTRATIVO LTDA'],
 'MEDICAL': ['MEDICAL SERVIÇOS'],
 'SERVIÇOS': ['SERVIÇOS DOMÉSTICOS LEANDRO VAZ'],
 'MOMMA': ['MOMMA DOCES SAUDAVEIS LTDA',
           'MOMMA DOCES SAUDAVEIS filial',
           'MOMMA BRUNCH - FILIAL MOMMA',
           'MOMMA AGUAS CLARAS -FILIAL DA MOMMA',
           'MOMMA FABRICA - FILIAL DA MOMMA',
           'MOMMA BSB SHOPPING FILIAL'],
 'Marietta': ['MARIETTA COMERCIO DE ALIMENTOS LTDA - MATRIZ',
              'MARIETTA COMERCIO DE ALIMENTOS LTDA - FILIAL 409 SUL',
              'FILIAL MARIETTA I IGUATEMI',
              'FILIAL MARIETTA II - BRASILIA SHOPPING TOWER',
              'FILIAL MARIETTA III - TERRAÇO SHOP OCTOGONAL',
              'FILIAL MARIETTA IV TAGUATINGA SHOPPING',
              'FILIAL MARIETTA V - LAGO SUL',
              'FILIAL MARIETTA VI CASA PARK',
              'FILIAL MARIETTA VII - CONJUNTO NACIONAL',
              'FILIAL MARIETTA VIII - PARK SHOPPING',
              'FILIAL MARIETTA'],
 'VIDA': ['VIDA LEVE COMERCIO DE ALIMENTOS LTDA -PLAZA NORTE'],
 'PEDRA': ['PEDRA ANGULAR EMPREENDIMENTO IMOBILIARIO LTDA'],
 'MVB': ['MVB SERVIÇOS DE APOIO TÉCNICO E ADMINISTRATIVO LTDA'],
 'EZUZ': ['EZUZ MODA ESPORTIVA LTDA'],
 'GREENRIVER': ['GREENRIVER BIORREFINARIA LTDA'],
 'GERAR': ['GERAR COMERCIO DE MOVEIS PLANEJADOS LTDA'],
 'KC': ['KC serviços odontológicos'],
 'PLACE': ['PLACE GESTAO E ENTRETENIMENTO LTDA'],
 'MMM': ['MMM BUSINESS FINANCIAL'],
 'BRASILIA': ['BRASILIA MOBILIDADE',
              'BRASILIA MOBILIDADE ELETRICA ONE - ASA SUL LTDA',
              'BRASILIA MOBILIDADE GAMA FILIAL'],
 'CGUS': ['CGUS CLINICA GINECOLOGICA E UROLOGICA SARMENTO LTDA'],
 'PRODUTOR': ['PRODUTOR RURAL GABRIELA'],
 'QUITUTICES': ['QUITUTICES CONFEITARIA', 'QUITUTICES EMPORIO'],
 'DF': ['DF BLOCO'],
 'SIE Store': ['SIE STORE ITAIM LTDA',
               'SIE STORE LAGO SUL LTDA',
               'SIE STORE VNC LTDA MATRIZ',
               'SIE CAMPINAS',
               'SIEE ALPHAVILLE - EM CONSTITUIÇÃO',
               'SIEE VNC FILIAL DA 654'],
 'NUTROX': ['NUTROX NUTRICAO ANIMAL LTDA'],
 'OABLOCOS': ['OABLOCOS SERVIÇOS DE APOIO TECNICO E ADMINISTRATIVO LTDA'],
 'CLINICA': ['CLINICA FLOW PSICOLOGIA EIRELI'],
 'VILLALVA': ['VILLALVA E AKUAMOA'],
 'THS': ['THS TECNOLOGIA - 01-10-25', 'THS TECNOLOGIA FILIAL (em análise)', 'THS FILIAL SP'],
 'MARIANOS': ['MARIANOS E SILVA FABRICACAO DE PAES LTDA (Incrivel Pão)'],
 'ATIVE': ['ATIVE FISIOTERAPIA 01-11-2025'],
 'AURORA': ['AURORA 01-11-2025'],
 'OURA': ['OURA PHARMA'],
 'CODE': ['CODE CENTRO 01-11-25'],
 'TICO': ['TICO LIRO RESTAURANTE'],
 'THULEP': ['THULEP BRASILIA LTDA 01-12-25'],
 'JC': ['JC AGRO LTDA'],
 'TERMAX': ['TERMAX 01-01-26', 'TERMAX FILIAL MT'],
 'MARQUES': ['MARQUES INFRAESTRUTURA  01-01-26'],
 'BEBI': ['BEBI CAFE 01-01-26'],
 'INTEGRATIVA': ['INTEGRATIVA MATRIZ 01-01-26', 'INTEGRATIVA FILIAL 01-01-26'],
 'Gabi': ['INSTITUTO RELUZ DE FONOAUDIOLOGIA LTDA 01-03-26', 'GABI MARZONI FONOAUDIOLOGIA LTDA 01-03-26'],
 'Instituto Medicina do Movimento': ['INSTITUTO DE MEDICINA DO MOVIMENTO INTEGRADO - LTDA 01-07',
                                     'INSTITUTO DE MEDICINA DO MOVIMENTO DE BRASILIA 01-07'],
 'BRL': ['BRL DESENVOLVIMENTO E TREINAMENTO 01-03-26'],
 '2L': ['2L COMUNICAÇÃO E PUBLICIDADE LTDA 01-03-26'],
 '2 Ellis Comunicação': ['2 ELLIS COMUNICAÇÃO E PUBLICIDADE LTDA0 01-03-26'],
 'YOD': ['YOD'],
 'HOMEM': ['HOMEM 360 LTDA'],
 'VICTORIA': ['VICTORIA ART GALLERY LTDA'],
 'LUMINE': ['LUMINE'],
 'SAUCE': ['SAUCE CONCEPT LTDA'],
 'GRATIA': ['GRATIA S.A'],
 'JRP': ['JRP SERVIÇOS'],
 'BEE': ['BEE PILATES SARAH BRANDAO - EM CONSTITUIÇÃO'],
 'MOSCA': ['MOSCA BRANCA  unidade Park Sul - EM CONSTITUIÇÃO'],
 'AVREN': ['AVREN INVESTIMENTOS LTDA', 'AVREN 2 INVESTIMENTOS LTDA', 'AVREN AGRO'],
 'RAS': ['RAS PRODUÇÃO DE EVENTOS LTDA'],
 'G&V': ['G&V SERVIÇOS MÉDICOS'],
 'IRINEU': ['IRINEU FARINA LTDA'],
 'Pitaluga': ['PITALUGA PRESTAÇÃO DE SERVIÇOS',
              'OTTANI PRESTACAO DE SERVICOS MEDICOS E CIRURGICOS LTDA 01-07',
              'DRA BRUNA PITALUGA CURSOS ONLINE E ASSESSORIA MEDICA EIRELI 01-07'],
 'CLICK': ['CLICK LOCAÇÃO FITNESS ALPHA - EM CONSTITUIÇÃO', 'CLICK LOCAÇÃO FITNESS BH - EM CONSTITUIÇÃO'],
 'AVRIUM': ['AVRIUM FINANCE LTDA'],
 'BISS': ['BISS ENTRETENIMENTO LTDA'],
 'LIVE': ['LIVE BETTER SOCIETY LTDA'],
 'EMVF': ['EMVF GESTAO MEDICA LTDA'],
 'BRUNA': ['BRUNA BORGES SERVICOS MEDICOS LTDA 01-08'],
 'NM': ['NM ADMINISTRACAO DE IMOVEIS PROPRIOS LTDA 01-08'],
 'RB': ['RB ODONTOLOGIA'],
 'VALORE': ['VALORE MARKET PLACE LTDA'],
 'BFF': ['BFF COMERCIO E DISTRIBUICAO DE ALIMENTOS LTDA - EM CONSTITUIÇÃO'],
 'Conecta': ['Conecta Nefro LTDA 01-09-26'],
 'PH': ['PH CURY LTDA - EM CONSTITUIÇÃO'],
 'CL': ['CL PINHEIROS COMERCIO DE ALIMENTOS LTDA - EM CONSTITUIÇÃO'],
 'Bolos do Flávio': ['BOLOS DO FLÁVIO MATRIZ ASA SUL (FJC COMERCIO DE PRODUTOS ALIMENTICIOS LTDA)',
                     'BOLOS DO FLÁVIO FILIAL POSTO (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL GUARÁ (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL BAHAMAS (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL CONTAINER (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL LOJA FÁBRICA E GALPÃO ADE (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL ASA NORTE (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL SAMAMBAIA (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL PONTE ALTA (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL RECANTO DAS EMAS (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL GAMA (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL NOROESTE (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL CONUNTO NACIONAL (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL ASA NORTE 307 (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL SAMAMBAIA SUL (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL SAMAMBAIA NORTE (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL BERNARDO SAYÂO (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL SIA DIA A DIA (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL DEPOSITO ÁGUAS CLARAS (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL FÁBRICA SCIA (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL CENTRAL SOBRADINHO (matriz 744)',
                     'BOLOS DO FLÁVIO FILIAL QUADRA 01 SOBRADINHO (matriz 744)',
                     'BOLOS DO FLÁVIO MATRIZ QUADRA 1 (F & R BOLOS DO FLAVIO LTDA)',
                     'BOLOS DO FLÁVIO FILIAL ARNIQUEIRAS (matriz 767)',
                     'BOLOS DO FLÁVIO MATRIZ CENTRAL (CENTRAL BOLOS COMERCIAL DE ALIMENTOS LTDA)',
                     'BOLOS DO FLÁVIO MATRIZ GILBERTO (WILSON AYUB NETO)',
                     'BOLOS DO FLÁVIO MATRIZ JARDIM BOTÂNICO (RR BOLOS DO FLAVIO LTDA)',
                     'BOLOS DO FLÁVIO MATRIZ ANTIGA ALPHAVILLE (RR BOLOS DO FLAVIO LTDA)',
                     'BOLOS DO FLÁVIO FILIAL PINHEIROS (matriz 772)',
                     'BOLOS DO FLÁVIO MATRIZ LOJA EPNB (RAYANA CAROLINE RIBEIRO DA COSTA)',
                     'BOLOS DO FLÁVIO MATRIZ FRANQUEADORA (FF FRANQUIAS LTDA)']}
